env:
  es2021: true
  node: true
  browser: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ['/dist']
rules: {
  import/extensions: [2, "ignorePackages"]
}

